select = ["ALL"]
ignore = [
    "ANN",
    "D104",
    "D105",
    "D107",
    "FBT",
    "PLR0911",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PTH",
    "S310",
    "S607",
    "SIM105",
]
unfixable = [
    "ERA001",
    "F401",
    "F841",
    "F842",
]

line-length = 79
target-version = "py38"

[per-file-ignores]
"__init__.py" = ["F401"]

[isort]
force-single-line = true
required-imports = [
    "from __future__ import annotations",
]

[pydocstyle]
convention = "google"
